<?php
//namespace ;

/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
use Thrift\Base\TBase;
use Thrift\Type\TType;
use Thrift\Type\TMessageType;
use Thrift\Exception\TException;
use Thrift\Exception\TProtocolException;
use Thrift\Protocol\TProtocol;
use Thrift\Exception\TApplicationException;


$GLOBALS['JavaConstants_CONSTANTS']['NUM_NODES_ALL'] = 0;

$GLOBALS['JavaConstants_CONSTANTS']['NUM_NODES_ALL_RACKS'] = -1;

$GLOBALS['JavaConstants_CONSTANTS']['INVALID_PLAN_NODE_ID'] = -1;

$GLOBALS['JavaConstants_CONSTANTS']['DEFAULT_PARTITION_ID'] = -1;

$GLOBALS['JavaConstants_CONSTANTS']['COMPRESSION_MAP'] = array(
  "" =>   0,
  "none" =>   0,
  "deflate" =>   1,
  "gzip" =>   2,
  "bzip2" =>   3,
  "snappy" =>   4,
);

$GLOBALS['JavaConstants_CONSTANTS']['DEFAULT_QUERY_OPTIONS'] = array(
    0 => "false",
    1 => "0",
    2 => "false",
    3 => "0",
    4 => "0",
    5 => "0",
    6 => "0",
    7 => "0",
    8 => "false",
    9 => "-1",
);


